<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Lauren Conner" />
    <meta name="description" content="Describe your website">
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>project 2</title>
    <meta name="generator" content="Hugo 0.70.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/blog/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="/resume.pdf/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/project2/">project 2</a></strong>
          </h3>
        </div>
        <div class="blog-title">
          <h4>
          January 1, 0001
            &nbsp;&nbsp;
            
          </h4>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="lauren-conner-lmc3757" class="section level2">
<h2>Lauren Conner Lmc3757</h2>
<p><em>INTRODUCTION:</em></p>
<p><em>In this project, I will be analyzing the dataset originated from R, presidentialElections from the pacakge pscl that is the democratic share of the presidential vote dated back from 1932-2016 taken by state. This includes a character variable, which is the State that the correlating election data took place in; the binary and simultaneously categorical variable is whether or not this state was considered one of the 11 states of the former Confederacy (“south”); the numerical variables are percent of the vote for president won by the Democratic candidate and year/integer that the election occured.</em> <em>There are 1,047 observations in the data with absences from Alabama data during years 1948 and 1964; Alaska and Hawaii contributed later (1960 on) while D.C. added data starting in 1964. This project is in a way trying to see if democratic votership increased or weighed in more for Presidency conducted in Southern or Northern territories of the United States.</em></p>
<ol style="list-style-type: decimal">
<li>(15 pts) Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all doesn’t make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss assumptions and whether or not they are likely to have been met (2).</li>
</ol>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ────────────────────────────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✔ ggplot2 3.2.1     ✔ purrr   0.3.3
## ✔ tibble  2.1.3     ✔ dplyr   0.8.3
## ✔ tidyr   1.0.3     ✔ stringr 1.4.0
## ✔ readr   1.3.1     ✔ forcats 0.4.0</code></pre>
<pre><code>## ── Conflicts ───────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>library(dplyr)
library(lmtest)</code></pre>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<pre class="r"><code>library(ggplot2)
library(pscl)</code></pre>
<pre><code>## Classes and Methods for R developed in the
## Political Science Computational Laboratory
## Department of Political Science
## Stanford University
## Simon Jackman
## hurdle and zeroinfl functions by Achim Zeileis</code></pre>
<pre class="r"><code>library(sandwich)
library(glmnet)</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## 
## Attaching package: &#39;Matrix&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:tidyr&#39;:
## 
##     expand, pack, unpack</code></pre>
<pre><code>## Loading required package: foreach</code></pre>
<pre><code>## 
## Attaching package: &#39;foreach&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:purrr&#39;:
## 
##     accumulate, when</code></pre>
<pre><code>## Loaded glmnet 2.0-16</code></pre>
<pre class="r"><code>?presidentialElections
glimpse(presidentialElections)</code></pre>
<pre><code>## Observations: 1,097
## Variables: 4
## $ state   &lt;chr&gt; &quot;Alabama&quot;, &quot;Arizona&quot;, &quot;Arkansas&quot;, &quot;California&quot;, &quot;Colorado&quot;, &quot;…
## $ demVote &lt;dbl&gt; 84.76, 67.03, 86.27, 58.41, 54.81, 47.40, 48.11, 74.49, 91.60…
## $ year    &lt;int&gt; 1932, 1932, 1932, 1932, 1932, 1932, 1932, 1932, 1932, 1932, 1…
## $ south   &lt;lgl&gt; TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FA…</code></pre>
<pre class="r"><code>#renaming the dataset
PE&lt;-presidentialElections
PE$year &lt;- as.factor(PE$year)
PE$south &lt;- factor(PE$south)

#MANOVA (1 TEST)
mano&lt;-manova(cbind(year,south)~demVote, data=presidentialElections)
summary(mano)</code></pre>
<pre><code>##             Df   Pillai approx F num Df den Df    Pr(&gt;F)    
## demVote      1 0.096349   58.322      2   1094 &lt; 2.2e-16 ***
## Residuals 1095                                              
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>#ANOVA (2 TESTS)
summary.aov(mano)</code></pre>
<pre><code>##  Response year :
##               Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## demVote        1  62043   62043  106.62 &lt; 2.2e-16 ***
## Residuals   1095 637174     582                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response south :
##               Df  Sum Sq Mean Sq F value  Pr(&gt;F)   
## demVote        1   1.518 1.51752   8.935 0.00286 **
## Residuals   1095 185.976 0.16984                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>#both are significant variables in regards to how they affect democratic votership
#year F(1,1095) = 106.62, p &lt; .0001 
#south F(1,1095) = 8.935, p = .00286

#post hoc t-test (4 TESTS)
pairwise.t.test(PE$demVote, PE$south, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  PE$demVote and PE$south 
## 
##      FALSE 
## TRUE 0.0029
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>#p-value is 0.0029 -&gt; significant
pairwise.t.test(PE$year, PE$south, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## Warning in mean.default(X[[i]], ...): argument is not numeric or logical:
## returning NA

## Warning in mean.default(X[[i]], ...): argument is not numeric or logical:
## returning NA</code></pre>
<pre><code>## Warning in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm): Calling var(x) on a factor x is deprecated and will become an error.
##   Use something like &#39;all(duplicated(x)[-1L])&#39; to test for a constant vector.

## Warning in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm): Calling var(x) on a factor x is deprecated and will become an error.
##   Use something like &#39;all(duplicated(x)[-1L])&#39; to test for a constant vector.</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  PE$year and PE$south 
## 
##      FALSE
## TRUE -    
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>#p-value is 0.76 -&gt; insignificant

#probability of type I error:
1-0.95^7</code></pre>
<pre><code>## [1] 0.3016627</code></pre>
<pre class="r"><code>#0.302 probability

#bonferroni testing: 
0.05/7</code></pre>
<pre><code>## [1] 0.007142857</code></pre>
<pre class="r"><code>#0.00714 </code></pre>
<p><em>Overall MANOVA is significant, so univariate ANOVAs were run to see which are significant which ended up being both year and south on democratic votership (p-values listed under ANOVAS). 4 post hoc t-tests were run for a total of of 7 tests run on the data. Additionally, there was a 0.302 probability that there was a type I error made that it would show false significance. Using the new bonferroni adjusted alpha value of 0.00714, it was found that the p-value for the pairwise t-test of demVote and south was still significant (0.0029) and the p-value for the year and south remained insignificant (0.76).</em></p>
<ol start="2" style="list-style-type: decimal">
<li>(10 pts) Perform some kind of randomization test on your data (that makes sense). This can be anything you want! State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distribution and the test statistic (3).</li>
</ol>
<pre class="r"><code>#H0 &amp; HA listed in description below...

#RANDOMIZATION TEST

#the actual observed test statistic (actual mean difference)
obs_diff&lt;-(PE%&gt;%filter(south==&quot;TRUE&quot;)%&gt;%summarize(mean(demVote)))-(PE%&gt;%filter(south==&quot;FALSE&quot;)%&gt;%summarize(mean(demVote)))
#2.752

#random distribution vector
rand_dist&lt;-vector()
for(i in 1:5000){
new&lt;-data.frame(demVote=sample(PE$demVote), south=PE$south)
rand_dist[i]&lt;-mean(new[new$south==&quot;TRUE&quot;,]$demVote) - mean(new[new$south==&quot;FALSE&quot;,]$demVote)}

#plot visualizing the null distribution and the test statistic
{hist(rand_dist,main=&quot;&quot;,ylab=&quot;&quot;); abline(v = 2.752,col=&quot;red&quot;)}</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<pre class="r"><code>#two tailed t value
mean(rand_dist&gt;2.752 | rand_dist&lt; -2.752)</code></pre>
<pre><code>## [1] 0.0036</code></pre>
<pre class="r"><code>#0.0044 is the computed two-tailed p-value

#compared with Welch&#39;s test
t.test(data=PE,demVote~south)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  demVote by south
## t = -2.3255, df = 293.38, p-value = 0.02073
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -5.0809665 -0.4229611
## sample estimates:
## mean in group FALSE  mean in group TRUE 
##            47.75733            50.50929</code></pre>
<pre class="r"><code>#t value of -2.326
#df = 293,38
#p-value = 0.0207 (still significant and slightly smaller p-value as we make assumptions and non-parametric tests like randomization tests are more conservative)</code></pre>
<p><em>H0=All groups for south=True and south=False will have the same mean of democratic votership that would contribute to Presidency (will equate to 0 for mean difference).</em> <em>Ha=The groups’ true difference in means for south=True and south=False of democratic votership that would contribute to Presidency is not equal to 0.</em> <em>The 2.752 mean difference could be seen on the random distribution histogram performed. 0.0044 is the computed two-tailed p-value; still significant in comparison to alpha of 0.05. Afterwards, compared with Welch’s test, which is robust to violations of homoskedasticity, but still assumes normality, the p-value was found to be 0.0207. This is still significant and slightly smaller p-value as we make assumptions and non-parametric tests like randomization tests are more conservative.</em></p>
<ol start="3" style="list-style-type: decimal">
<li>(35 pts) Build a linear regression model predicting one of your response variables from at least 2 other variables, including their interaction. Mean-center any numeric variables involved in the interaction. – Interpret the coefficient estimates (do not discuss significance) (10) – Plot the regression using ggplot(). If your interaction is numeric by numeric, refer to code near the end of WS15 to make the plot. If you have 3 or more predictors, just chose two to plot for convenience. (8) – Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test (4) – Regardless, recompute regression results with robust standard errors via coeftest(…, vcov=vcovHC(…)). Discuss significance of results, including any changes from before/after robust SEs if applicable. (8) – What proportion of the variation in the outcome does your model explain? (4)</li>
</ol>
<pre class="r"><code>#center numeric variables
PE$demVote_c&lt;- (PE$demVote - mean(PE$demVote, na.rm = T))

#linear regression
fitten&lt;-lm(demVote_c~south*year, data=PE, na.rm=T)</code></pre>
<pre><code>## Warning: In lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) :
##  extra argument &#39;na.rm&#39; will be disregarded</code></pre>
<pre class="r"><code>summary(fitten)</code></pre>
<pre><code>## 
## Call:
## lm(formula = demVote_c ~ south * year, data = PE, na.rm = T)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -35.843  -4.388   0.259   4.009  45.494 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           8.297      1.427   5.812 8.15e-09 ***
## southTRUE            26.706      2.982   8.957  &lt; 2e-16 ***
## year1936              2.578      2.019   1.277  0.20192    
## year1940             -3.877      2.019  -1.921  0.05505 .  
## year1944             -5.565      2.019  -2.757  0.00594 ** 
## year1948             -6.434      2.019  -3.187  0.00148 ** 
## year1952            -15.725      2.019  -7.790 1.60e-14 ***
## year1956            -16.508      2.019  -8.178 8.27e-16 ***
## year1960             -8.611      1.993  -4.321 1.70e-05 ***
## year1964              6.312      1.980   3.187  0.00148 ** 
## year1968            -11.954      1.980  -6.036 2.19e-09 ***
## year1972            -18.294      1.980  -9.238  &lt; 2e-16 ***
## year1976             -8.663      1.980  -4.374 1.34e-05 ***
## year1980            -18.504      1.980  -9.344  &lt; 2e-16 ***
## year1984            -16.770      1.980  -8.468  &lt; 2e-16 ***
## year1988            -10.292      1.980  -5.197 2.43e-07 ***
## year1992            -14.858      1.980  -7.503 1.33e-13 ***
## year1996             -8.308      1.980  -4.195 2.96e-05 ***
## year2000             -9.955      1.980  -5.027 5.86e-07 ***
## year2004             -8.905      1.980  -4.497 7.66e-06 ***
## year2008             -3.536      1.980  -1.785  0.07447 .  
## year2012             -6.163      1.980  -3.112  0.00191 ** 
## year2016            -10.513      1.993  -5.276 1.60e-07 ***
## southTRUE:year1936   -2.735      4.217  -0.649  0.51676    
## southTRUE:year1940    1.421      4.217   0.337  0.73625    
## southTRUE:year1944   -2.708      4.217  -0.642  0.52095    
## southTRUE:year1948  -30.994      4.297  -7.213 1.05e-12 ***
## southTRUE:year1952  -13.744      4.217  -3.259  0.00115 ** 
## southTRUE:year1956  -17.512      4.217  -4.153 3.55e-05 ***
## southTRUE:year1960  -24.622      4.204  -5.856 6.32e-09 ***
## southTRUE:year1964  -41.798      4.279  -9.767  &lt; 2e-16 ***
## southTRUE:year1968  -42.444      4.199 -10.109  &lt; 2e-16 ***
## southTRUE:year1972  -37.214      4.199  -8.863  &lt; 2e-16 ***
## southTRUE:year1976  -19.508      4.199  -4.646 3.81e-06 ***
## southTRUE:year1980  -18.625      4.199  -4.436 1.01e-05 ***
## southTRUE:year1984  -28.879      4.199  -6.878 1.04e-11 ***
## southTRUE:year1988  -32.469      4.199  -7.733 2.44e-14 ***
## southTRUE:year1992  -25.759      4.199  -6.135 1.20e-09 ***
## southTRUE:year1996  -28.524      4.199  -6.794 1.82e-11 ***
## southTRUE:year2000  -29.892      4.199  -7.120 2.00e-12 ***
## southTRUE:year2004  -32.408      4.199  -7.719 2.72e-14 ***
## southTRUE:year2008  -35.190      4.199  -8.381  &lt; 2e-16 ***
## southTRUE:year2012  -33.657      4.199  -8.016 2.88e-15 ***
## southTRUE:year2016  -31.602      4.204  -7.517 1.20e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.682 on 1053 degrees of freedom
## Multiple R-squared:  0.5475, Adjusted R-squared:  0.5291 
## F-statistic: 29.63 on 43 and 1053 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>#{demVote}= 2.726 + 18.851(SOUTH) - 0.2850(YEAR)

#plotted regression using ggplot
PE%&gt;%ggplot(aes(x=year,y=demVote_c, color=south))+geom_point()+geom_smooth(method = &#39;lm&#39;,se=F)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<pre class="r"><code>#check assumptions of linearity, normality, and homoskedasticity

#linearity
resids&lt;-fitten$residuals
fitvals&lt;-fitten$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, color=&#39;red&#39;)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-2-2.png" width="672" /></p>
<pre class="r"><code>#This plot shows that it the data does not meet linearity

#normality
shapiro.test(resids)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resids
## W = 0.92873, p-value &lt; 2.2e-16</code></pre>
<pre class="r"><code>#p-value was significant and therefore violated normality

#homoskedasticity test
bptest(fitten)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fitten
## BP = 73.265, df = 43, p-value = 0.00272</code></pre>
<pre class="r"><code>#BP Test shows the violation of homoskedasticity as the p-value is extremely significant.

#redone with robust standard errors 
#uncorrected SEs 
summary(fitten)$coef[,1:2]</code></pre>
<pre><code>##                      Estimate Std. Error
## (Intercept)          8.296548   1.427381
## southTRUE           26.705872   2.981703
## year1936             2.577568   2.018622
## year1940            -3.877027   2.018622
## year1944            -5.565135   2.018622
## year1948            -6.434324   2.018622
## year1952           -15.724595   2.018622
## year1956           -16.507568   2.018622
## year1960            -8.610818   1.992574
## year1964             6.311554   1.980411
## year1968           -11.953696   1.980411
## year1972           -18.294446   1.980411
## year1976            -8.662696   1.980411
## year1980           -18.504446   1.980411
## year1984           -16.769696   1.980411
## year1988           -10.292196   1.980411
## year1992           -14.858446   1.980411
## year1996            -8.307696   1.980411
## year2000            -9.954946   1.980411
## year2004            -8.905446   1.980411
## year2008            -3.535946   1.980411
## year2012            -6.162696   1.980411
## year2016           -10.513125   1.992574
## southTRUE:year1936  -2.734840   4.216764
## southTRUE:year1940   1.420663   4.216764
## southTRUE:year1944  -2.707592   4.216764
## southTRUE:year1948 -30.994494   4.297257
## southTRUE:year1952 -13.743587   4.216764
## southTRUE:year1956 -17.512432   4.216764
## southTRUE:year1960 -24.621910   4.204357
## southTRUE:year1964 -41.798372   4.279440
## southTRUE:year1968 -42.444486   4.198606
## southTRUE:year1972 -37.213736   4.198606
## southTRUE:year1976 -19.508213   4.198606
## southTRUE:year1980 -18.624645   4.198606
## southTRUE:year1984 -28.879395   4.198606
## southTRUE:year1988 -32.468713   4.198606
## southTRUE:year1992 -25.758827   4.198606
## southTRUE:year1996 -28.524122   4.198606
## southTRUE:year2000 -29.892327   4.198606
## southTRUE:year2004 -32.408190   4.198606
## southTRUE:year2008 -35.190418   4.198606
## southTRUE:year2012 -33.657304   4.198606
## southTRUE:year2016 -31.602329   4.204357</code></pre>
<pre class="r"><code>#corrected SE
coeftest(fitten, vcov = vcovHC(fitten))[,1:2]</code></pre>
<pre><code>##                      Estimate Std. Error
## (Intercept)          8.296548   1.225335
## southTRUE           26.705872   3.848615
## year1936             2.577568   1.671950
## year1940            -3.877027   1.513776
## year1944            -5.565135   1.472576
## year1948            -6.434324   1.502059
## year1952           -15.724595   1.593858
## year1956           -16.507568   1.460027
## year1960            -8.610818   1.481613
## year1964             6.311554   1.738354
## year1968           -11.953696   1.988642
## year1972           -18.294446   1.858237
## year1976            -8.662696   1.740595
## year1980           -18.504446   1.963535
## year1984           -16.769696   1.992775
## year1988           -10.292196   1.804989
## year1992           -14.858446   1.936355
## year1996            -8.307696   1.950484
## year2000            -9.954946   2.190915
## year2004            -8.905446   2.190106
## year2008            -3.535946   2.232340
## year2012            -6.162696   2.379846
## year2016           -10.513125   2.433017
## southTRUE:year1936  -2.734840   5.133435
## southTRUE:year1940   1.420663   5.006622
## southTRUE:year1944  -2.707592   5.165967
## southTRUE:year1948 -30.994494   7.230100
## southTRUE:year1952 -13.743587   4.759305
## southTRUE:year1956 -17.512432   4.779322
## southTRUE:year1960 -24.621910   4.446005
## southTRUE:year1964 -41.798372   6.182087
## southTRUE:year1968 -42.444486   4.516570
## southTRUE:year1972 -37.213736   4.250679
## southTRUE:year1976 -19.508213   4.458307
## southTRUE:year1980 -18.624645   4.406882
## southTRUE:year1984 -28.879395   4.201385
## southTRUE:year1988 -32.468713   4.123710
## southTRUE:year1992 -25.758827   4.369456
## southTRUE:year1996 -28.524122   4.286850
## southTRUE:year2000 -29.892327   4.371769
## southTRUE:year2004 -32.408190   4.365318
## southTRUE:year2008 -35.190418   4.544820
## southTRUE:year2012 -33.657304   4.613056
## southTRUE:year2016 -31.602329   4.727759</code></pre>
<pre class="r"><code>#Rsquared=proportion of the variation in the outcome the model explains as 0.103</code></pre>
<p><em>In the year 1932 (reference year), in a non-Southern state, there would be democratic votership of 8.297%.</em> <em>Another example is with the year 1948, in a non-Southern state, democratic votership went down 6.434% and would have involvement of 1.863%.</em> <em>Most of the interactions (which would be translated as the slopes) are significant in the relationship of year and identification of a southern territory votership.</em> <em>This linear regression model plotted predicts, from the variables year and southern identification, the democratic vote response.</em> <em>The linearity was tested and the plot made did not meet linearity; normality was tested with Shapiro Wilke’s test and the p-value was significant and therefore violated normality; and lastly, BP Test shows the violation of homoskedasticity as the p-value is extremely significant.</em> <em>In the corrected SE section, intercept SE decreased when corrected while the south indicator increased as did most of the interaction standard errors of south and year. Lastly, R^2 is the proportion of the variation in the outcome the model explains, which would be 0.5291 in this model, which is all predictors at once.</em></p>
<ol start="4" style="list-style-type: decimal">
<li>(5 pts) Rerun same regression model (with interaction), but this time compute bootstrapped standard errors. Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)</li>
</ol>
<pre class="r"><code>#bootstrap residuals 5000 replication
sampledist&lt;-replicate(5000,{
boot_dat&lt;- sample_frac(PE,replace=T)
fittey&lt;-lm(demVote_c~south*year, data=boot_dat)
coef(fittey) })

boot_dat&lt;- sample_frac(PE,replace=T)
fittey&lt;-lm(demVote_c~south*year, data=boot_dat)
coeftest(fittey)</code></pre>
<pre><code>## 
## t test of coefficients:
## 
##                     Estimate Std. Error  t value  Pr(&gt;|t|)    
## (Intercept)         10.92465    1.26538   8.6335 &lt; 2.2e-16 ***
## southTRUE           15.43995    3.87958   3.9798 7.370e-05 ***
## year1936            -0.47751    2.04639  -0.2333 0.8155409    
## year1940            -7.31258    1.80039  -4.0617 5.234e-05 ***
## year1944            -9.03166    1.75018  -5.1604 2.944e-07 ***
## year1948            -8.81454    1.80039  -4.8959 1.132e-06 ***
## year1952           -18.87143    1.78951 -10.5456 &lt; 2.2e-16 ***
## year1956           -19.05027    1.75944 -10.8275 &lt; 2.2e-16 ***
## year1960           -11.65382    1.77908  -6.5505 8.954e-11 ***
## year1964             3.29081    1.87686   1.7534 0.0798312 .  
## year1968           -10.50782    1.69412  -6.2025 7.971e-10 ***
## year1972           -20.83283    1.80039 -11.5713 &lt; 2.2e-16 ***
## year1976           -10.78405    1.74127  -6.1932 8.439e-10 ***
## year1980           -20.83405    1.87686 -11.1005 &lt; 2.2e-16 ***
## year1984           -19.48937    1.74127 -11.1926 &lt; 2.2e-16 ***
## year1988           -13.30705    1.81175  -7.3449 4.118e-13 ***
## year1992           -17.81071    1.86259  -9.5624 &lt; 2.2e-16 ***
## year1996           -10.33013    1.75018  -5.9023 4.828e-09 ***
## year2000           -10.00950    1.90763  -5.2471 1.868e-07 ***
## year2004           -11.59972    1.84898  -6.2736 5.144e-10 ***
## year2008            -7.13957    1.83600  -3.8886 0.0001071 ***
## year2012           -11.14540    1.84898  -6.0279 2.295e-09 ***
## year2016           -13.95984    2.26730  -6.1570 1.053e-09 ***
## southTRUE:year1936  13.46442    4.87352   2.7628 0.0058312 ** 
## southTRUE:year1940   6.16716    5.12820   1.2026 0.2294028    
## southTRUE:year1944   6.35321    4.89747   1.2972 0.1948318    
## southTRUE:year1948 -23.89518    5.12820  -4.6596 3.574e-06 ***
## southTRUE:year1952   1.25743    4.67176   0.2692 0.7878630    
## southTRUE:year1956   1.23927    4.82395   0.2569 0.7973067    
## southTRUE:year1960 -11.93518    5.27478  -2.2627 0.0238580 *  
## southTRUE:year1964 -27.38981    4.86801  -5.6265 2.356e-08 ***
## southTRUE:year1968 -34.88772    4.63606  -7.5253 1.126e-13 ***
## southTRUE:year1972 -26.11784    4.72181  -5.5313 4.009e-08 ***
## southTRUE:year1976  -7.03113    4.52082  -1.5553 0.1201805    
## southTRUE:year1980  -8.55662    4.94416  -1.7307 0.0838068 .  
## southTRUE:year1984 -17.56797    5.26215  -3.3386 0.0008717 ***
## southTRUE:year1988 -21.81410    5.13220  -4.2504 2.323e-05 ***
## southTRUE:year1992 -15.70790    4.70023  -3.3419 0.0008612 ***
## southTRUE:year1996 -16.55529    4.61699  -3.5857 0.0003516 ***
## southTRUE:year2000 -20.69757    4.71827  -4.3867 1.267e-05 ***
## southTRUE:year2004 -20.06628    4.85733  -4.1311 3.896e-05 ***
## southTRUE:year2008 -25.44309    4.61564  -5.5124 4.452e-08 ***
## southTRUE:year2012 -19.41860    4.85733  -3.9978 6.839e-05 ***
## southTRUE:year2016 -20.06316    5.03145  -3.9875 7.137e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><em>In bootstrapping the standard errors, it is found that the p-values for year, democratic vote, and the interaction of south and democratic votership are remained significant. Std. Error increased for all a little besides democratic vote, which slightly decreased.</em></p>
<ol start="5" style="list-style-type: decimal">
<li>(40 pts) Perform a logistic regression predicting a binary categorical variable (if you don’t have one, make/get one) from at least two explanatory variables (interaction not necessary). – Interpret coefficient estimates in context (10) – Report a confusion matrix for your logistic regression (2) – Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), and Recall (PPV) of your model (5) – Using ggplot, plot density of log-odds (logit) by your binary outcome variable (3) – Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret</li>
</ol>
<ol start="10" style="list-style-type: decimal">
<li>– Perform 10-fold (or repeated random sub-sampling) CV and report average out-of-sample Accuracy, Sensitivity, and Recall (10)</li>
</ol>
<pre class="r"><code>class_diag &lt;- function(probs,truth){
  
  #CONFUSION MATRIX: CALCULATE ACCURACY, TPR, TNR, PPV
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]

  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  
  #CALCULATE EXACT AUC
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

  data.frame(acc,sens,spec,ppv,auc)
}

#GLM
fit2&lt;-glm(south~demVote_c+year,data=PE, family=binomial(link = &quot;logit&quot;))

#COEFTEST
coeftest(fit2)</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##               Estimate Std. Error z value  Pr(&gt;|z|)    
## (Intercept) -1.6021696  0.3669403 -4.3663 1.264e-05 ***
## demVote_c    0.0248262  0.0069613  3.5663  0.000362 ***
## year1936    -0.0426748  0.4911747 -0.0869  0.930764    
## year1940     0.0904833  0.4922501  0.1838  0.854158    
## year1944     0.1619230  0.4932684  0.3283  0.742711    
## year1948     0.2552451  0.5092368  0.5012  0.616209    
## year1952     0.4880091  0.5098213  0.9572  0.338458    
## year1956     0.5329255  0.5134872  1.0379  0.299337    
## year1960     0.3278953  0.5006884  0.6549  0.512539    
## year1964    -0.0928006  0.4977474 -0.1864  0.852099    
## year1968     0.4656818  0.5124188  0.9088  0.363460    
## year1972     0.6024190  0.5256042  1.1461  0.251735    
## year1976     0.2712530  0.4983081  0.5443  0.586202    
## year1980     0.5066582  0.5159488  0.9820  0.326103    
## year1984     0.5209599  0.5176906  1.0063  0.314264    
## year1988     0.3816985  0.5057432  0.7547  0.450412    
## year1992     0.4572615  0.5118725  0.8933  0.371690    
## year1996     0.3090523  0.5006930  0.6172  0.537070    
## year2000     0.3520704  0.5035715  0.6991  0.484460    
## year2004     0.3390392  0.5027851  0.6743  0.500106    
## year2008     0.2179160  0.4957736  0.4395  0.660265    
## year2012     0.2721639  0.4986705  0.5458  0.585218    
## year2016     0.3954791  0.5057380  0.7820  0.434224    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>#Intercept: -4.956
#demVote_c: .0176
#year: .00186

#CLASSIFICATION DIAGNOSTICS
prob2&lt;-predict(fit2, type = &quot;response&quot;)
class_diag(prob2,PE$south)</code></pre>
<pre><code>##            acc sens spec ppv       auc
## TRUE 0.7812215    0    1 NaN 0.5389148</code></pre>
<pre class="r"><code>#CONFUSION MATRIX
table(predict=as.numeric(prob2&gt;.5), truth=PE$south)%&gt;%addmargins()</code></pre>
<pre><code>##        truth
## predict FALSE TRUE  Sum
##     0     857  240 1097
##     Sum   857  240 1097</code></pre>
<pre class="r"><code>#Accuracy, Sensitivity (TPR), Specificity (TNR), and Recall (PPV) of model
#TPR/True Positive Rate: 0/240 = 0
#TNR/True Negative Rate: 857/857 = 1
#PPV: 0/0 = 0
#This means the model did not predict any of them as South/1.

#GGPLOT: density of log-odds (logit) by your binary outcome variable 
PE$logit&lt;-predict(fit2,type=&quot;link&quot;) #get predicted logit scores (logodds)

PE%&gt;%ggplot()+geom_density(aes(logit,color=south,fill=south), alpha=.4)+
  theme(legend.position=c(.85,.85))+geom_vline(xintercept=0)+xlab(&quot;predictor (logit)&quot;)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre class="r"><code>#The logit density plot showed everything as non-southern

#ROC curve (plot) and calculate AUC
library(plotROC)
ROCplot&lt;-ggplot(PE)+geom_roc(aes(d=south,m=prob2), n.cuts=0) 
ROCplot</code></pre>
<pre><code>## Warning in verify_d(data$d): D not labeled 0/1, assuming FALSE = 0 and TRUE = 1!</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>## Warning in verify_d(data$d): D not labeled 0/1, assuming FALSE = 0 and TRUE = 1!</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.5389148</code></pre>
<pre class="r"><code>#AUC is 0.534 with a weak ROC plot

#10-fold (or repeated random sub-sampling) CV and report average out-of-sample Accuracy, Sensitivity, and Recall

class_diag(prob2,PE$south)</code></pre>
<pre><code>##            acc sens spec ppv       auc
## TRUE 0.7812215    0    1 NaN 0.5389148</code></pre>
<pre class="r"><code>#10-FOLD CV:

set.seed(1234)
k=10 #choose number of folds

data&lt;-PE[sample(nrow(PE)),] #randomly order rows
folds&lt;-cut(seq(1:nrow(PE)),breaks=k,labels=F) #create folds

diags&lt;-NULL
for(i in 1:k){
  ## Create training and test sets
  train&lt;-data[folds!=i,] 
  test&lt;-data[folds==i,]
  
  truth&lt;-test$south ## Truth labels for fold i
  
  ## Train model on training set (all but fold i)
  fit3&lt;-glm(south~demVote+year,data=train, family=&quot;binomial&quot;)
  
  ## Test model on test set (fold i) 
  probs3&lt;-predict(fit3,newdata = test,type=&quot;response&quot;)
  
  ## Get diagnostics for fold i
  diags&lt;-rbind(diags,class_diag(probs3,truth))
}

summarize_all(diags,mean) #average diagnostics across all k folds</code></pre>
<pre><code>##         acc sens spec ppv       auc
## 1 0.7812927    0    1 NaN 0.4322446</code></pre>
<pre class="r"><code>#report average out-of-sample Accuracy, Sensitivity, and Recall

#Accuracy: 0.781
#Sensitivity: 0
#Recall: NaN
#about same performance out-of-sample; not overfitting, just model was hard to predict non-south.</code></pre>
<p><em>The coefficients in context are : Intercept = -4.956 demVote_c = .0176 year = .00186. This means that the best fitting line would be {south} = -4.956 + .0176(demVote) + year(.00186). On an average year, with average democratic votership, southern votership would decrease by -4.956. For every one unit increase in democratic votership, the chances of the outcome being Southern would decrease by 4.9384.</em> <em>Accuracy, Sensitivity (TPR), Specificity (TNR), and Recall (PPV) of model</em> #TPR/True Positive Rate: 0/240 = 0 #TNR/True Negative Rate: 857/857 = 1 #Recall/PPV: 0/0 = 0 #This means the model did not predict any of them as South/1. <em>The logit density plot showed everything as non-southern; shows the model is bad at predicting, consistent with the TPR, TNR, and PPV rates.</em> <em>AUC calculated is 0.539 with a weak ROC plot and therefore is not a reliable model that could be an indication of a lot of false negatives or positives.</em> <em>In reporting the average out-of-sample Accuracy, Sensitivity, and Recall there was about the same performance out-of-sample; not overfitting, just model was hard to predict non-south.</em> #Accuracy: 0.781 #Sensitivity: 0 #Recall/PPV: NaN</p>
<ol start="6" style="list-style-type: decimal">
<li>(10 pts) Choose one variable you want to predict (can be one you used from before; either binary or continuous) and run a LASSO regression inputting all the rest of your variables as predictors. Choose lambda to give the simplest model whose accuracy is near that of the best (i.e., lambda.1se). Discuss which variables are retained. Perform 10-fold CV using this model: if response in binary, compare model’s out-of-sample accuracy to that of your logistic regression in part 5; if response is numeric, compare the residual standard error (at the bottom of the summary output, aka RMSE): lower is better fit!</li>
</ol>
<pre class="r"><code>#recoding variables
datnew&lt;-PE%&gt;%select(-demVote_c,-logit)
y&lt;-as.matrix(datnew$south)
x&lt;-model.matrix(south~., data=datnew)[,-1]

#LASSO
cv&lt;-cv.glmnet(x,y, family=&quot;binomial&quot;)
lasso1&lt;-glmnet(x,y,family=&quot;binomial&quot;,lambda=cv$lambda.1se)
coef(lasso1)</code></pre>
<pre><code>## 73 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                              s0
## (Intercept)           4.3171496
## stateAlaska         -12.0355092
## stateArizona        -12.2378038
## stateArkansas         3.5049161
## stateCalifornia     -12.2446777
## stateColorado       -12.2381468
## stateConnecticut    -12.2432328
## stateDC             -12.0565927
## stateDelaware       -12.2436617
## stateFlorida          3.5081245
## stateGeorgia          3.5013576
## stateHawaii         -12.0576251
## stateIdaho          -12.2300919
## stateIllinois       -12.2443810
## stateIndiana        -12.2362819
## stateIowa           -12.2410349
## stateKansas         -12.2316479
## stateKentucky       -12.2403968
## stateLouisiana        3.5065522
## stateMaine          -12.2398399
## stateMaryland       -12.2474491
## stateMassachusetts  -12.2503446
## stateMichigan       -12.2434256
## stateMinnesota      -12.2464331
## stateMississippi      3.5083846
## stateMissouri       -12.2434298
## stateMontana        -12.2393306
## stateNebraska       -12.2310376
## stateNevada         -12.2418972
## stateNew Hampshire  -12.2389506
## stateNew Jersey     -12.2434529
## stateNew Mexico     -12.2440905
## stateNew York       -12.2482935
## stateNorth Carolina   3.5052065
## stateNorth Dakota   -12.2347174
## stateOhio           -12.2415676
## stateOklahoma       -12.2377016
## stateOregon         -12.2444186
## statePennsylvania   -12.2443580
## stateRhode Island   -12.2527988
## stateSouth Carolina   3.5045814
## stateSouth Dakota   -12.2369742
## stateTennessee        3.5077758
## stateTexas            3.5041000
## stateUtah           -12.2321120
## stateVermont        -12.2412685
## stateVirginia         3.5078661
## stateWashington     -12.2461781
## stateWest Virginia  -12.2446818
## stateWisconsin      -12.2445472
## stateWyoming        -12.2102304
## demVote               0.0011602
## year1936              .        
## year1940              .        
## year1944              .        
## year1948              .        
## year1952              .        
## year1956              .        
## year1960              .        
## year1964              .        
## year1968              .        
## year1972              .        
## year1976              .        
## year1980              .        
## year1984              .        
## year1988              .        
## year1992              .        
## year1996              .        
## year2000              .        
## year2004              .        
## year2008              .        
## year2012              .        
## year2016              .</code></pre>
<pre class="r"><code>#All variables are retained besides &#39;year&#39;.

x&lt;-as.data.frame(x)
y&lt;-as.data.frame(y)
bound&lt;-bind_cols(x,y)
bound&lt;-bound%&gt;%rename(south = `V1`)

#10-FOLD CV (only use significant predictors)
set.seed(1234)
k=10
data &lt;- bound[sample(nrow(bound)),] #put rows of dataset in random order
folds &lt;- cut(seq(1:nrow(bound)),breaks=k,labels=F) #create fold labels

diags&lt;-NULL
for(i in 1:k){
  train &lt;- data[folds!=i,] #create training set (all but fold i)
  test &lt;- data[folds==i,] #create test set (just fold i)
  truth &lt;- test$south #save truth labels from fold i
  
fitness &lt;- glm(south ~ stateAlaska+stateArizona+stateArkansas+stateCalifornia+stateColorado+stateConnecticut+stateDC+stateDelaware+stateFlorida+stateGeorgia+stateHawaii+stateIdaho + stateIllinois+stateIndiana +stateIowa+stateKansas+stateKentucky  +stateLouisiana+stateMaine+stateMaryland+stateMassachusetts+stateMichigan+stateMinnesota+ stateMississippi+stateMissouri+stateMontana+stateNebraska+stateNevada+`stateNew Hampshire`+`stateNew Jersey`+`stateNew Mexico`+`stateNew York`+`stateNorth Carolina`+`stateNorth Dakota`+stateOhio+stateOklahoma+stateOregon+statePennsylvania+`stateRhode Island`+`stateSouth Carolina`+`stateSouth Dakota`+stateTennessee+stateTexas+stateUtah+stateVermont+stateVirginia+stateWashington+`stateWest Virginia`+stateWisconsin+stateWyoming + demVote, data=train, family=&quot;binomial&quot;, maxit=1100)
  probs &lt;- predict(fitness, newdata=test, type=&quot;response&quot;)
  diags&lt;-rbind(diags,class_diag(probs,truth))
}

summarize_all(diags,mean) #AVERAGE THE DIAGNOSTICS ACROSS THE 10 FOLDS</code></pre>
<pre><code>##   acc sens spec ppv auc
## 1   1    1    1   1   1</code></pre>
<p><em>All of the variables are retained except for the variable year within the lasso analysis. There was an apparent accurate prediction of all acc, sens, spec, ppv, and auc. I know I am so sorry I must have done something horribly different or horribly right at this point I am unsure since it all ran.</em></p>
</div>

              <hr>
              <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
