baseurl = "/"
languageCode = "en-US"
title = "Portfolio"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "fullsizeoutput_83ac.jpeg"
  author = "Lauren Conner"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Email         = "lmc3757@utexas.edu"
  LinkedIn      = "lauren-conner-571441154"
  Instagram     = "justadashofginger"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "Project1"
  identifier = "Project1"
  weight = 200
  url = "/Projects/"
[[menu.main]]
  name = "Project2"
  identifier = "Project2"
  weight = 200
  url = "/Projects/"
[[menu.main]]
  name = "_Resume_Version2"
  identifier = "_Resume_Version2"
  weight = 300
  url = "/Resume/"
